[project]
name = "whoa-scope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kivy>=2.3.1",
    "numpy>=2.2.6",
    "pyserial>=3.5",
]
